export type Store = {
    count: number
    inc: () => void
}

export type getUsersState = {
    getUsers: () => Promise<UsersData[]>
    // post: UsersData[]
}
// Generated by https://quicktype.io

export interface UsersData {
    _id:       string;
    name:      string;
    password:  string;
    email:     string;
    img:       string;
    role:      string;
    google:    boolean;
    createdAt: string;
    updatedAt: string;
}

